@baseUrl = http://localhost:8080

POST {{baseUrl}}/autores
Content-Type: application/json

{
    "nome": "Diego",
    "email": "diego@gmail.com",
    "descricao": "Desenvolvedor java"
}
###
POST {{baseUrl}}/categorias
Content-Type: application/json

{
    "nome": "Arquitetura de Software"
}

###
POST {{baseUrl}}/livros
Content-Type: application/json

{
  "titulo": "Spring Boot",
  "resumo": "resumo",
  "sumario": "sumario",
  "preco": 100.00,
  "numeroDePaginas": 140,
  "isbn": "234123",
  "dataDePublicacao": "20/05/2021",
  "categoriaId": 1,
  "autorId": 1
}
###
POST {{baseUrl}}/livros
Content-Type: application/json

{
  "titulo": "Java 16",
  "resumo": "resumo",
  "sumario": "sumario",
  "preco": 110.00,
  "numeroDePaginas": 140,
  "isbn": "23324123",
  "dataDePublicacao": "10/10/2021",
  "categoriaId": 1,
  "autorId": 1
}
###
GET {{baseUrl}}/livros
###
GET {{baseUrl}}/livros/1
###
POST {{baseUrl}}/paises
Content-Type: application/json

{
    "nome": "Argentina"
}
###
POST {{baseUrl}}/paises
Content-Type: application/json

{
    "nome": "Portugal"
}
###
POST {{baseUrl}}/estados
Content-Type: application/json

{
    "nome": "Rio de Janeiro",
    "paisId": 1
}
###
POST {{baseUrl}}/cupons
Content-Type: application/json

{
    "codigo": "DEV2021",
    "percentualDeDesconto": 30,
    "validade": "10/04/2022"
}
###
POST {{baseUrl}}/compras/
Content-Type: application/json

{
    "email": "diegors90@gmail.com",
    "nome": "Diego",
	"sobrenome": "Sousa",
	"documento": "528.626.500-64",
	"endereco": "Rua Jardim",
    "complemento": "Quadra 3",
	"cidade": "Catolé do Rocha",
	"paisId": 1,
	"estadoId": 1,
	"telefone": "83999999999",
	"cep": "58884000",
    "total": "100.00",
    "codigoCupom": "XBS100",
    "itensCompraRequest": [
        {
            "livroId": 1,
            "quantidade": 2
        },
        {
            "livroId": 2,
            "quantidade": 1
        }
    ]

}

###
POST {{baseUrl}}/compras/
Content-Type: application/json

{
    "email": "diegors90@gmail.com",
    "nome": "Diego",
	"sobrenome": "Sousa",
	"documento": "528.626.500-64",
	"endereco": "Rua Jardim",
    "complemento": ".",
	"cidade": "Catolé do Rocha",
	"paisId": 2,
	"telefone": "83999999999",
	"cep": "58884000",
    "total": "100.00",
    "itensCompraRequest": [
        {
            "livroId": 1,
            "quantidade": 2
        },
        {
            "livroId": 2,
            "quantidade": 1
        }
    ]

}


###
GET {{baseUrl}}/compras/2