@baseUrl = http://localhost:8080

POST {{baseUrl}}/autores
Content-Type: application/json

{
    "nome": "Diego",
    "email": "diego@gmail.com",
    "descricao": "Desenvolvedor java"
}
###
POST {{baseUrl}}/categorias
Content-Type: application/json

{
    "nome": "Java"
}

###
POST {{baseUrl}}/livros
Content-Type: application/json

{
  "titulo": "Spring Boot",
  "resumo": "resumo",
  "sumario": "sumario",
  "preco": 100.00,
  "numeroDePaginas": 140,
  "isbn": "234123",
  "dataDePublicacao": "20/05/2021",
  "categoriaId": 1,
  "autorId": 1
}
###
GET {{baseUrl}}/livros
###
GET {{baseUrl}}/livros/1
###
POST {{baseUrl}}/paises
Content-Type: application/json

{
    "nome": "Brasil"
}
###
POST {{baseUrl}}/estados
Content-Type: application/json

{
    "nome": "Paraíba",
    "paisId": 1
}
###
POST {{baseUrl}}/compras
Content-Type: application/json

{
    "email": "diegors90@gmail.com",
    "nome": "Diego",
	"sobrenome": "Sousa",
	"documento": "528.626.500-64",
	"endereco": "Rua Jardim",
    "complemento": ".",
	"cidade": "Catolé do Rocha",
	"paisId": 1,
	"estadoId": 1,
	"telefone": "83999999999",
	"cep": "58884000"
}